server.port=6000
spring.application.name=qma-service
server.forward-headers-strategy=framework

spring.datasource.url=${QMA_DB_URL:jdbc:postgresql://127.0.0.1:5432/quantity_measurement}
spring.datasource.username=${QMA_DB_USERNAME:}
spring.datasource.password=${QMA_DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
